# Generated by Django 3.2.9 on 2021-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=500)),
                ('EMAIL', models.CharField(max_length=1000)),
                ('CHOSEN_PASS', models.CharField(max_length=1000)),
                ('USERNAME', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
