# Generated by Django 3.2.9 on 2021-12-13 12:39

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20211202_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default=datetime.datetime(2021, 12, 13, 12, 39, 2, 259596, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
