# Generated by Django 3.2.9 on 2022-01-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20211213_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
