# Generated by Django 3.2.9 on 2022-01-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_auto_20220124_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
