# Generated by Django 3.2.9 on 2022-01-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_alter_uploadedimage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='date',
            field=models.DateField(),
        ),
    ]
