# Generated by Django 3.2.9 on 2022-01-26 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_alter_uploadedimage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
