# Generated by Django 3.2.9 on 2022-01-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_alter_uploadedimage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='images',
            new_name='image',
        ),
    ]
