# Generated by Django 3.2.9 on 2022-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0018_auto_20220206_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(default='', upload_to='Uploaded_Image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(default='Posted on 2022-02-06 14:00:46.012654', max_length=200000000000000000),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='uploaded on'),
        ),
    ]
