# Generated by Django 3.2.9 on 2022-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0019_auto_20220206_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(default='Posted on 2022-02-06 14:38:22.688159', max_length=200000000000000000),
        ),
    ]
