# Generated by Django 3.2.9 on 2022-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0020_alter_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(default='Posted on 2022-02-06 15:02:08.090896', max_length=200000000000000000),
        ),
    ]
