# Generated by Django 3.2.9 on 2022-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0021_alter_posts_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(default='Posted on 2022-02-06 15:08:41.184744', max_length=200000000000000000),
        ),
    ]
