# Generated by Django 3.2.9 on 2022-02-06 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0022_auto_20220206_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(default='deafult.jpg', upload_to='Uploaded_Image/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(default='Posted on 2022-02-06 15:21:20.033544', max_length=200000000000000000),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
