# Generated by Django 3.2.9 on 2022-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0024_auto_20220207_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='Posted on 2022-02-07 21:58:37.386043', max_length=200000000000000000),
        ),
    ]
