# Generated by Django 3.2.9 on 2022-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0027_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='Posted on 2022-02-07 22:51:33.551034', max_length=200000000000000000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='Post_images/'),
        ),
    ]
