# Generated by Django 3.2.9 on 2022-02-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0029_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='Posted on 2022-02-10 22:20:00.416922', max_length=200000000000000000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='Post_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(blank=True, default='deafult.jpg', upload_to='Uploaded_Image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
