# Generated by Django 3.2.9 on 2022-02-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0033_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default='Posted on 2022-02-15 21:32:47.050696', max_length=200000000000000000, null=True),
        ),
    ]
